"""
Unit tests for the public `checkers` package interface.

This suite provides smoke-level coverage for the public API. These tests are intended as broad API-level checks and can be extended with edge-case or property-based tests as needed.

Example Usage (from project root):
    # Run test suite:
    python -m unittest tests.checkers.test_interfaces

Dependencies:
    - Python >= 3.9
    - Standard Library: unittest, dataclasses
    - Internal:
        - src.checkers.interfaces
        - src.models.interfaces (Bom, Board, Header, Row)
        - tests._fixtures (sample valid objects for convenience)

Design Notes & Assumptions:
    - Uses shared fixtures (`_HEADER`, `_ROW_ONE`, `_BOM`, etc.) for consistency.
    - Invalid scenarios are generated by cloning and mutating fixture objects with `dataclasses.replace`.
    - Focuses on API-level behavior, leaving detailed field/logic validation to lower-level rule and checker tests.

License:
 - Internal Use Only
"""

import unittest
import src.checkers.interfaces as checkers

from dataclasses import replace
from tests.fixtures import v3_bom as bfx


class TestCheckV3Bom(unittest.TestCase):
    """
    Unit tests for `check_v3_bom`.
    """

    def test_valid_bom(self):
        """
        Should return an empty string when all boards (headers + rows) are valid.
        """
        # ARRANGE
        bom = bfx.BOM_B

        # ACT
        text_str = checkers.check_v3_bom(bom)

        # ASSERT
        with self.subTest("Error msg length", Out=len(text_str), Exp=0):
            self.assertEqual(len(text_str), 0)

    def test_invalid_bom(self):
        """
        Should return a non-empty string when any board has invalid header or rows.
        """
        # ARRANGE
        bom = replace(
            bfx.BOM_A,
            boards=(
                replace(
                    bfx.BOARD_A,
                    header=replace(bfx.BOARD_A.header, overhead_cost="99.99"),
                ),
            ),
        )

        # ACT
        text_str = checkers.check_v3_bom(bom)

        # ASSERT
        with self.subTest("Type", Out=type(text_str).__name__, Exp="str"):
            self.assertIsInstance(text_str, str)
        with self.subTest("Error msg length", Out=len(text_str), Exp=">0"):
            self.assertNotEqual(len(text_str), 0)


if __name__ == "__main__":
    unittest.main()
